<div class="offcanvas offcanvas-end team-editor" tabindex="-1" id="team-editor" aria-labelledby="team-editor-title" data-bs-backdrop="static">
    <div class="offcanvas-header"><div><span class="team-eyebrow">КОМАНДА ТА ДОСТУПИ</span><h2 id="team-editor-title">{{ $editingUser ? 'Редагувати користувача' : 'Новий користувач' }}</h2></div><button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Закрити форму"></button></div>
    <form method="POST" action="{{ $editingUser ? route('settings.team.update', $editingUser) : route('settings.team.store') }}" data-team-form class="team-editor-form">
        @csrf
        <input type="hidden" name="_method" value="{{ $editingUser ? 'PATCH' : 'POST' }}">
        <input type="hidden" name="_team_form" value="{{ $formKey }}">
        <div class="offcanvas-body">
            <p class="team-editor-intro" data-team-editor-intro>{{ $editingUser ? 'Налаштуйте логін і доступи цього користувача.' : 'Створіть обліковий запис для нового учасника команди.' }}</p>
            <div class="team-form-section"><span>01</span><h3>Обліковий запис</h3></div>
            <div class="mb-3"><label for="team-name" class="form-label">Ім’я</label><input id="team-name" name="name" class="form-control {{ $formErrors->has('name') ? 'is-invalid' : '' }}" value="{{ $fieldValue('name', $editingUser?->name ?? '') }}" maxlength="255" @readonly($editingUser) @required(!$editingUser) autocomplete="off"></div>
            <div class="mb-3"><label for="team-email" class="form-label">Email</label><input id="team-email" name="email" type="email" class="form-control {{ $formErrors->has('email') ? 'is-invalid' : '' }}" value="{{ $fieldValue('email', $editingUser?->email ?? '') }}" maxlength="255" @readonly($editingUser) @required(!$editingUser) autocomplete="off"></div>
            <div class="mb-4"><label for="team-username" class="form-label">Логін <span class="team-muted fw-normal">· необов’язково</span></label><input id="team-username" name="username" class="form-control {{ $formErrors->has('username') ? 'is-invalid' : '' }}" value="{{ $fieldValue('username', $editingUser?->username ?? '') }}" placeholder="Наприклад, міша" maxlength="64" autocomplete="off" autocapitalize="none" spellcheck="false" aria-describedby="team-username-help" aria-invalid="{{ $formErrors->has('username') ? 'true' : 'false' }}"><div class="invalid-feedback" data-team-field-error>{{ $formErrors->first('username') }}</div><div id="team-username-help" class="form-text">Українські або латинські літери, цифри, крапка, дефіс, підкреслення. Без логіна вхід залишається за email.</div></div>
            <div class="team-form-section"><span>02</span><h3>Доступ до CRM</h3></div>
            <div class="mb-3"><label for="team-role" class="form-label">Роль</label><select id="team-role" name="role" class="form-select {{ $formErrors->has('role') ? 'is-invalid' : '' }}" required>@foreach($roleOptions as $value => $label)<option value="{{ $value }}" @selected($fieldValue('role', $editingUser?->roleKey() ?? 'operator') === $value)>{{ $label }}</option>@endforeach</select></div>
            <div class="mb-4" data-team-status-field @unless($editingUser) hidden @endunless><label for="team-active" class="form-label">Статус</label><select id="team-active" name="is_active" class="form-select {{ $formErrors->has('is_active') ? 'is-invalid' : '' }}"><option value="1" @selected((bool) $fieldValue('is_active', $editingUser?->is_active ?? true))>Активний — може входити</option><option value="0" @selected(!(bool) $fieldValue('is_active', $editingUser?->is_active ?? true))>Заблокований — вхід вимкнено</option></select></div>
            <div class="team-form-section"><span>03</span><h3 data-team-password-title>{{ $editingUser ? 'Змінити пароль' : 'Пароль для входу' }}</h3></div>
            <p class="form-text" data-team-password-help>{{ $editingUser ? 'Залиште поля порожніми, щоб зберегти поточний пароль.' : 'Передайте пароль користувачу особисто.' }}</p>
            <div class="mb-3"><label for="team-password" class="form-label">Пароль</label><input id="team-password" name="password" type="password" class="form-control {{ $formErrors->has('password') ? 'is-invalid' : '' }}" autocomplete="new-password" @required(!$editingUser)></div>
            <div class="mb-3"><label for="team-password-confirmation" class="form-label">Підтвердіть пароль</label><input id="team-password-confirmation" name="password_confirmation" type="password" class="form-control" autocomplete="new-password" @required(!$editingUser)></div>
        </div>
        <div class="team-editor-footer"><span data-team-draft-note class="team-muted" hidden>Є незбережені зміни</span><div><button type="button" class="btn team-edit" data-bs-dismiss="offcanvas">Закрити</button><button type="submit" class="btn team-primary" data-team-save>{{ $editingUser ? 'Зберегти зміни' : 'Створити користувача' }}</button></div></div>
    </form>
</div>
