[program:domcrm-novapay]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/domcrm.com.ua/current/artisan queue:work database --queue=novapay --sleep=3 --tries=20 --timeout=75 --max-time=3600
directory=/var/www/domcrm.com.ua/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=deploy
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/domcrm.com.ua/shared/storage/logs/novapay-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=90
